name: Atualizar Main

on:
  workflow_dispatch:
  
jobs:
  create-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
            
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        id: cpr
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Atualizar main a partir de dev
          committer: GitHub <noreply@github.com>
          author: GitHub Actions <actions@github.com>
          branch: temp-sync-branch
          delete-branch: true
          title: 'Atualizar main a partir de dev'
          body: |
            Atualização automática do branch main a partir do branch dev
            
            [Criado automaticamente por GitHub Actions]
          base: main
          
      - name: Enable Auto-merge
        if: steps.cpr.outputs.pull-request-operation == 'created'
        run: |
          PR_NUMBER="${{ steps.cpr.outputs.pull-request-number }}"
          echo "Habilitando auto-merge para PR #$PR_NUMBER"
          
          # Tentar fazer merge via API
          curl -X PUT \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/merge" \
            -d '{"merge_method":"merge"}'