name: DEV 2 MAIN

on:
  workflow_dispatch:

jobs:
  pr-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Create PR
        id: create-pr
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/pulls \
            -d '{
              "title": "Merge DEV to MAIN via API",
              "head": "dev",
              "base": "main",
              "body": "Automated PR via direct API"
            }'
