name: Rollback DEV to Latest Stable MAIN

on:
  workflow_dispatch:

jobs:
  rollback-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: dev
          fetch-depth: 0
          
      - name: Fetch main branch
        run: |
          git fetch origin main
          echo "Obtendo a última versão estável do main..."
          MAIN_COMMIT=$(git rev-parse origin/main)
          echo "Commit estável do main: $MAIN_COMMIT"
      
      - name: Reset dev to main version
        run: |
          # Reset o branch dev para o mesmo estado do main
          git reset --hard origin/main
          
          # Force push para atualizar o branch dev remoto
          git push --force origin dev
          
          echo "Branch dev foi resetado para a última versão estável do main!"
      
      - name: Deploy to Dev Server
        env:
          SSH_PASS: 9TKSUsh2PAV
        run: |
          sudo apt-get install -y sshpass rsync
          export SSHPASS=$SSH_PASS
          
          # Usar rsync com a opção --delete para excluir arquivos que não existem mais
          sshpass -e rsync -avz --delete --exclude="node_modules" -e "ssh -o StrictHostKeyChecking=no" ./ root@157.230.229.74:/root/wpp-multiatendimento/dev/
          
          # Reiniciar a aplicação
          sshpass -e ssh -o StrictHostKeyChecking=no root@157.230.229.74 'cd /root/wpp-multiatendimento/dev && npm install && export BRANCH=dev && pm2 delete wpp-multiatendimento-dev || true && PORT=3001 BRANCH=dev pm2 start index.js --name wpp-multiatendimento-dev'
          
          echo "Branch dev restaurado para a versão estável do main e sincronizado com a VPS!"