name: Rollback DEV to Backup Version

on:
  workflow_dispatch:

jobs:
  rollback-dev:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: dev
          fetch-depth: 0
          
      - name: Fetch backup branch
        run: |
          git fetch origin backup
          echo "Obtendo a última versão do backup..."
          
          # Verificar se a branch backup existe
          BACKUP_EXISTS=$(git ls-remote --heads origin backup | wc -l)
          
          if [ "$BACKUP_EXISTS" -eq "0" ]; then
            echo "::error::Branch backup não existe! É necessário criar um backup primeiro."
            exit 1
          fi
          
          BACKUP_COMMIT=$(git rev-parse origin/backup)
          echo "Commit do backup: $BACKUP_COMMIT"
      
      - name: Reset dev to backup version
        run: |
          # Reset o branch dev para o mesmo estado do backup
          git reset --hard origin/backup
          
          # Force push para atualizar o branch dev remoto
          git push --force origin dev
          
          echo "Branch dev foi resetado para a versão de backup!"
      
      - name: Deploy to Dev Server
        env:
          SSH_PASS: 9TKSUsh2PAV
        run: |
          sudo apt-get install -y sshpass rsync
          export SSHPASS=$SSH_PASS
          
          # Usar rsync com a opção --delete para excluir arquivos que não existem mais
          sshpass -e rsync -avz --delete --exclude="node_modules" -e "ssh -o StrictHostKeyChecking=no" ./ root@157.230.229.74:/root/wpp-multiatendimento/dev/
          
          # Reiniciar a aplicação
          sshpass -e ssh -o StrictHostKeyChecking=no root@157.230.229.74 'cd /root/wpp-multiatendimento/dev && npm install && export BRANCH=dev && pm2 delete wpp-multiatendimento-dev || true && PORT=3001 BRANCH=dev pm2 start index.js --name wpp-multiatendimento-dev'
          
          echo "Branch dev restaurado para a versão de backup e sincronizado com a VPS!"