name: Sincronização Final

on:
  workflow_dispatch:
  
jobs:
  api-direto:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Criar PR e fazer merge
        id: create-pr
        run: |
          # Criar PR usando curl
          PR_RESPONSE=$(curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/pulls \
            -d '{
              "title": "Sincronizar Dev para Main via API",
              "head": "dev",
              "base": "main",
              "body": "PR criado automaticamente via API direta"
            }')
          
          # Extrair número do PR
          PR_NUMBER=$(echo $PR_RESPONSE | grep -o '"number": [0-9]*' | grep -o '[0-9]*' | head -1)
          
          echo "PR criado: #$PR_NUMBER"
          echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT
          
          if [ ! -z "$PR_NUMBER" ]; then
            # Fazer merge do PR
            MERGE_RESPONSE=$(curl -X PUT \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/merge \
              -d '{
                "commit_title": "Mesclar dev em main via API",
                "commit_message": "Mesclagem automatizada via API direta",
                "merge_method": "merge"
              }')
            
            echo "Resposta do merge: $MERGE_RESPONSE"
          else
            echo "Falha ao criar PR"
            exit 1
          fi