name: Sync Direct Merge

on:
  workflow_dispatch:

jobs:
  direct-merge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
          
      - name: Fetch all branches
        run: git fetch --all
          
      - name: Configure Git
        run: |
          git config user.name "GitHub Action"
          git config user.email "actions@github.com"
          
      - name: Merge dev into main
        run: |
          echo "Buscando alterações do branch dev..."
          git fetch origin dev
          
          echo "Tentando mesclar dev em main..."
          git merge origin/dev -m "Merge dev into main via workflow"
          
          echo "Enviando alterações para o repositório remoto..."
          git push origin main