name: Sync Dev to Main

on:
  workflow_dispatch:
  
jobs:
  sync-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Sync dev to main via PR
        run: |
          # Criar um PR de dev para main e fazer merge automaticamente
          PR_RESPONSE=$(curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/gmpartners/wpp-multiatendimento/pulls \
            -d '{
              "title": "Sync Dev to Main via Workflow", 
              "head": "dev", 
              "base": "main", 
              "body": "Automated PR created by workflow"
            }')
          
          echo "PR Response: $PR_RESPONSE"
          
          # Extrair número do PR da resposta
          PR_NUMBER=$(echo $PR_RESPONSE | grep -o '"number": [0-9]*' | grep -o '[0-9]*' | head -1)
          
          if [ ! -z "$PR_NUMBER" ]; then
            echo "Created PR #$PR_NUMBER, now merging..."
            
            # Fazer merge do PR
            MERGE_RESPONSE=$(curl -X PUT -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/gmpartners/wpp-multiatendimento/pulls/$PR_NUMBER/merge \
              -d '{
                "commit_title": "Merge dev into main via workflow", 
                "commit_message": "Automated merge via GitHub Actions", 
                "merge_method": "merge"
              }')
              
            echo "Merge Response: $MERGE_RESPONSE"
          else
            echo "Failed to create PR or extract PR number"
            exit 1
          fi
      
      - name: Checkout main for deployment
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 1
          
      - name: Install sshpass and rsync
        run: sudo apt-get install -y sshpass rsync
          
      - name: Backup Current Production
        env:
          SSH_PASS: 9TKSUsh2PAV
        run: |
          export SSHPASS=$SSH_PASS
          timestamp=$(date +%Y%m%d_%H%M%S)
          sshpass -e ssh -o StrictHostKeyChecking=no root@157.230.229.74 'mkdir -p /root/wpp-multiatendimento/backup/$timestamp && cp -r /root/wpp-multiatendimento/main/* /root/wpp-multiatendimento/backup/$timestamp/ || true'
          
      - name: Deploy to Production Server
        env:
          SSH_PASS: 9TKSUsh2PAV
        run: |
          export SSHPASS=$SSH_PASS
          # Usar rsync com a opção --delete para excluir arquivos que não existem mais
          sshpass -e rsync -avz --delete --exclude="node_modules" -e "ssh -o StrictHostKeyChecking=no" ./ root@157.230.229.74:/root/wpp-multiatendimento/main/
          sshpass -e ssh -o StrictHostKeyChecking=no root@157.230.229.74 'cd /root/wpp-multiatendimento/main && npm install && export BRANCH=main && pm2 delete wpp-multiatendimento-main || true && PORT=3000 BRANCH=main pm2 start index.js --name wpp-multiatendimento-main'