name: Sync Dev to Main

on:
  workflow_dispatch:
  
jobs:
  sync-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository for sync
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main
      
      - name: Setup Git
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          
      - name: Print debug info
        run: |
          echo "Current branch:"
          git branch --show-current
          echo "All branches:"
          git branch -a
          echo "Local refs:"
          git show-ref
          
      - name: Fetch dev branch
        run: |
          git fetch origin dev
          
      - name: Create and merge PR
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "dev"
          destination_branch: "main"
          pr_title: "Sync Dev to Main"
          pr_body: "Automated PR to sync Dev to Main"
          pr_reviewer: ""
          pr_assignee: ""
          pr_label: "automerge"
          github_token: ${{ secrets.GITHUB_TOKEN }}