name: Sync Dev to Main

on:
  workflow_dispatch:
  
jobs:
  create-and-merge-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Create Pull Request
        id: create-pr
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: pr } = await github.rest.pulls.create({
              owner: 'gmpartners',
              repo: 'wpp-multiatendimento',
              title: 'Sync Dev to Main via Workflow',
              head: 'dev',
              base: 'main',
              body: 'Automated PR created by workflow to sync dev to main'
            });
            
            console.log(`Created PR #${pr.number}: ${pr.html_url}`);
            
            // Merge the PR immediately
            await github.rest.pulls.merge({
              owner: 'gmpartners',
              repo: 'wpp-multiatendimento',
              pull_number: pr.number,
              merge_method: 'merge',
              commit_title: 'Merge dev into main',
              commit_message: 'Automated merge via workflow'
            });
            
            console.log(`Merged PR #${pr.number}`);
            return pr.number;